### ISSUE TITLE
Docker pull must have a specific tag

### ISSUE THREAD

**Issue by hstdt** [zachgrayio/swift-tensorflow#2]
The `latest` can not be found.

```
docker pull zachgray/swift-tensorflow:4.2
docker run  --privileged --cap-add sys_ptrace -it --rm zachgray/swift-tensorflow:4.2 swift -I/usr/lib/swift/clang/include
```

<img width="591" alt="image" src="https://user-images.githubusercontent.com/10215098/39347518-cb9ee52e-4a25-11e8-8e11-422deda62750.png">

**Comment by zachgrayio** [comment]
@hstdt thanks for the heads up! I've pushed images tagged latest, as well as updated docs to include a specific tag anyways as it's best practice.

let me know if you have any other issues!
