### ISSUE TITLE
Docker command typo

### ISSUE THREAD

**Issue by dan-zheng** [zachgrayio/swift-tensorflow#4]
In the ["Run the interpreter"](https://github.com/zachgrayio/swift-tensorflow#run-the-interpreter) section of the README, there's a typo:

    docker --rm run -v ${PWD}:/usr/src zachgray/swift-tensorflow:4.2 swift -O /usr/src/inference.swift

In the command, `run` must come before `--rm`: `docker run --rm ...`.

**Comment by zachgrayio** [comment]
oops! 

late-night doc editing strikes again, on it.
